# GitHub Sponsors se activará cuando se complete la verificación del titular.
# Mientras tanto, estas son vías públicas y gratuitas de apoyo al proyecto.
custom:
  - "https://www.amazon.es/hz/wishlist/ls/19L0TUV1GMTIR?ref_=wl_share"
  - "https://danaaliramontes.github.io/"
